---
- set_fact: userno={{ item }}

- name: Create Tenant {{ item }}
  uri:
    url: https://master.{{ ocp_apps_domain }}/master/api/providers.xml
    method: POST
    return_content: yes
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body: "access_token=mastertoken&org_name={{ userno }}&username={{ userno }}&email=admin%40{{ userno }}.com&password=openshift"
    validate_certs: no
    status_code: 201
  register: create_tenant_result

- debug: var=create_tenant_result.content

- set_fact: signup={{ create_tenant_result.content }}

- name: Get Ids
  xml:
    xmlstring: '{{ signup }}'
    xpath: //account/id | //user[username='{{ userno }}']/id | //account/admin_domain | //account/domain
    content: text
  register: xmlstring

- debug: var=xmlstring.matches

- set_fact: ids={{ xmlstring.matches }}

- name: Activate Tenant User {{ item }}
  uri:
    url: https://master.{{ocp_apps_domain}}/admin/api/accounts/{{ ids[0].id }}/users/{{ ids[3].id }}/activate.xml
    method: PUT
    return_content: yes
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body: "access_token=mastertoken&account_id={{ ids[0].id }}&id={{ ids[3].id }}"
    validate_certs: no
    status_code: 200

- name: Create Admin Tenant {{ item }} Router
  shell: "oc create route edge system-provider-{{ userno }}-admin-route --service=system-provider --hostname={{ ids[1].admin_domain }} --port=http --insecure-policy=Allow -n {{ namespace }}"

- name: Create Developer Tenant {{ item }} Router
  shell: "oc create route edge system-developer-{{ userno }}-route --service=system-developer --hostname={{ ids[2].domain }} --port=http --insecure-policy=Allow -n {{ namespace }}"
